// Code generated by protoc-gen-go.
// source: scan2drive.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	scan2drive.proto

It has these top-level messages:
	DefaultUserRequest
	DefaultUserReply
	ProcessScanRequest
	ProcessScanReply
	ConvertRequest
	ConvertReply
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type DefaultUserRequest struct {
}

func (m *DefaultUserRequest) Reset()                    { *m = DefaultUserRequest{} }
func (m *DefaultUserRequest) String() string            { return proto1.CompactTextString(m) }
func (*DefaultUserRequest) ProtoMessage()               {}
func (*DefaultUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DefaultUserReply struct {
	User string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *DefaultUserReply) Reset()                    { *m = DefaultUserReply{} }
func (m *DefaultUserReply) String() string            { return proto1.CompactTextString(m) }
func (*DefaultUserReply) ProtoMessage()               {}
func (*DefaultUserReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DefaultUserReply) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type ProcessScanRequest struct {
	User string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
	Dir  string `protobuf:"bytes,2,opt,name=dir" json:"dir,omitempty"`
}

func (m *ProcessScanRequest) Reset()                    { *m = ProcessScanRequest{} }
func (m *ProcessScanRequest) String() string            { return proto1.CompactTextString(m) }
func (*ProcessScanRequest) ProtoMessage()               {}
func (*ProcessScanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProcessScanRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ProcessScanRequest) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

type ProcessScanReply struct {
}

func (m *ProcessScanReply) Reset()                    { *m = ProcessScanReply{} }
func (m *ProcessScanReply) String() string            { return proto1.CompactTextString(m) }
func (*ProcessScanReply) ProtoMessage()               {}
func (*ProcessScanReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ConvertRequest struct {
	ScannedPage [][]byte `protobuf:"bytes,1,rep,name=scanned_page,json=scannedPage,proto3" json:"scanned_page,omitempty"`
}

func (m *ConvertRequest) Reset()                    { *m = ConvertRequest{} }
func (m *ConvertRequest) String() string            { return proto1.CompactTextString(m) }
func (*ConvertRequest) ProtoMessage()               {}
func (*ConvertRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ConvertRequest) GetScannedPage() [][]byte {
	if m != nil {
		return m.ScannedPage
	}
	return nil
}

type ConvertReply struct {
	PDF []byte `protobuf:"bytes,1,opt,name=PDF,json=pDF,proto3" json:"PDF,omitempty"`
	// A thumbnail (PNG).
	Thumb []byte `protobuf:"bytes,2,opt,name=thumb,proto3" json:"thumb,omitempty"`
}

func (m *ConvertReply) Reset()                    { *m = ConvertReply{} }
func (m *ConvertReply) String() string            { return proto1.CompactTextString(m) }
func (*ConvertReply) ProtoMessage()               {}
func (*ConvertReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ConvertReply) GetPDF() []byte {
	if m != nil {
		return m.PDF
	}
	return nil
}

func (m *ConvertReply) GetThumb() []byte {
	if m != nil {
		return m.Thumb
	}
	return nil
}

func init() {
	proto1.RegisterType((*DefaultUserRequest)(nil), "proto.DefaultUserRequest")
	proto1.RegisterType((*DefaultUserReply)(nil), "proto.DefaultUserReply")
	proto1.RegisterType((*ProcessScanRequest)(nil), "proto.ProcessScanRequest")
	proto1.RegisterType((*ProcessScanReply)(nil), "proto.ProcessScanReply")
	proto1.RegisterType((*ConvertRequest)(nil), "proto.ConvertRequest")
	proto1.RegisterType((*ConvertReply)(nil), "proto.ConvertReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Scan service

type ScanClient interface {
	DefaultUser(ctx context.Context, in *DefaultUserRequest, opts ...grpc.CallOption) (*DefaultUserReply, error)
	ProcessScan(ctx context.Context, in *ProcessScanRequest, opts ...grpc.CallOption) (*ProcessScanReply, error)
	Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertReply, error)
}

type scanClient struct {
	cc *grpc.ClientConn
}

func NewScanClient(cc *grpc.ClientConn) ScanClient {
	return &scanClient{cc}
}

func (c *scanClient) DefaultUser(ctx context.Context, in *DefaultUserRequest, opts ...grpc.CallOption) (*DefaultUserReply, error) {
	out := new(DefaultUserReply)
	err := grpc.Invoke(ctx, "/proto.Scan/DefaultUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scanClient) ProcessScan(ctx context.Context, in *ProcessScanRequest, opts ...grpc.CallOption) (*ProcessScanReply, error) {
	out := new(ProcessScanReply)
	err := grpc.Invoke(ctx, "/proto.Scan/ProcessScan", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scanClient) Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertReply, error) {
	out := new(ConvertReply)
	err := grpc.Invoke(ctx, "/proto.Scan/Convert", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Scan service

type ScanServer interface {
	DefaultUser(context.Context, *DefaultUserRequest) (*DefaultUserReply, error)
	ProcessScan(context.Context, *ProcessScanRequest) (*ProcessScanReply, error)
	Convert(context.Context, *ConvertRequest) (*ConvertReply, error)
}

func RegisterScanServer(s *grpc.Server, srv ScanServer) {
	s.RegisterService(&_Scan_serviceDesc, srv)
}

func _Scan_DefaultUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServer).DefaultUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scan/DefaultUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServer).DefaultUser(ctx, req.(*DefaultUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scan_ProcessScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServer).ProcessScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scan/ProcessScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServer).ProcessScan(ctx, req.(*ProcessScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scan_Convert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServer).Convert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scan/Convert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServer).Convert(ctx, req.(*ConvertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scan_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Scan",
	HandlerType: (*ScanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DefaultUser",
			Handler:    _Scan_DefaultUser_Handler,
		},
		{
			MethodName: "ProcessScan",
			Handler:    _Scan_ProcessScan_Handler,
		},
		{
			MethodName: "Convert",
			Handler:    _Scan_Convert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scan2drive.proto",
}

func init() { proto1.RegisterFile("scan2drive.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xc1, 0x4e, 0xc2, 0x40,
	0x10, 0xa5, 0x16, 0x34, 0x0e, 0x8d, 0x69, 0x46, 0x8c, 0x95, 0x13, 0xee, 0xc1, 0x70, 0xe2, 0x00,
	0x89, 0x26, 0x5e, 0x69, 0x38, 0x37, 0x6b, 0x3c, 0x9b, 0xa5, 0x1d, 0x91, 0xa4, 0xb6, 0xeb, 0xee,
	0x96, 0x84, 0x4f, 0xf4, 0xaf, 0xcc, 0x2e, 0xb5, 0xa1, 0x94, 0x53, 0xa7, 0x6f, 0xe7, 0xbd, 0x79,
	0xef, 0x41, 0xa8, 0x53, 0x51, 0xcc, 0x33, 0xb5, 0xdd, 0xd1, 0x4c, 0xaa, 0xd2, 0x94, 0x38, 0x70,
	0x1f, 0x36, 0x02, 0x8c, 0xe9, 0x53, 0x54, 0xb9, 0x79, 0xd7, 0xa4, 0x38, 0xfd, 0x54, 0xa4, 0x0d,
	0x7b, 0x82, 0xb0, 0x85, 0xca, 0x7c, 0x8f, 0x08, 0xfd, 0x4a, 0x93, 0x8a, 0xbc, 0x89, 0x37, 0xbd,
	0xe6, 0x6e, 0x66, 0xaf, 0x80, 0x89, 0x2a, 0x53, 0xd2, 0xfa, 0x2d, 0x15, 0x45, 0xcd, 0x3e, 0xb7,
	0x89, 0x21, 0xf8, 0xd9, 0x56, 0x45, 0x17, 0x0e, 0xb2, 0x23, 0x43, 0x08, 0x5b, 0x5c, 0x99, 0xef,
	0xd9, 0x02, 0x6e, 0x96, 0x65, 0xb1, 0x23, 0x65, 0xfe, 0xb5, 0x1e, 0x21, 0xb0, 0xd6, 0x0b, 0xca,
	0x3e, 0xa4, 0xd8, 0x50, 0xe4, 0x4d, 0xfc, 0x69, 0xc0, 0x87, 0x35, 0x96, 0x88, 0x0d, 0xb1, 0x67,
	0x08, 0x1a, 0x92, 0x35, 0x1a, 0x82, 0x9f, 0xc4, 0x2b, 0x77, 0x3d, 0xe0, 0xbe, 0x8c, 0x57, 0x38,
	0x82, 0x81, 0xf9, 0xaa, 0xbe, 0xd7, 0xee, 0x7c, 0xc0, 0x0f, 0x3f, 0xf3, 0x5f, 0x0f, 0xfa, 0xf6,
	0x34, 0x2e, 0x61, 0x78, 0x94, 0x16, 0x1f, 0x0e, 0x0d, 0xcd, 0xba, 0xbd, 0x8c, 0xef, 0xcf, 0x3d,
	0x59, 0xe3, 0x3d, 0x2b, 0x72, 0x14, 0xa7, 0x11, 0xe9, 0xd6, 0xd3, 0x88, 0x74, 0xd2, 0xf7, 0xf0,
	0x05, 0xae, 0xea, 0x28, 0x78, 0x57, 0x6f, 0xb5, 0xfb, 0x18, 0xdf, 0x9e, 0xc2, 0x8e, 0xb8, 0xbe,
	0x74, 0xe8, 0xe2, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x06, 0x41, 0xfd, 0xe8, 0x01, 0x00, 0x00,
}
