// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ScanClient is the client API for Scan service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScanClient interface {
	DefaultUser(ctx context.Context, in *DefaultUserRequest, opts ...grpc.CallOption) (*DefaultUserReply, error)
	ProcessScan(ctx context.Context, in *ProcessScanRequest, opts ...grpc.CallOption) (*ProcessScanReply, error)
	Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertReply, error)
}

type scanClient struct {
	cc grpc.ClientConnInterface
}

func NewScanClient(cc grpc.ClientConnInterface) ScanClient {
	return &scanClient{cc}
}

func (c *scanClient) DefaultUser(ctx context.Context, in *DefaultUserRequest, opts ...grpc.CallOption) (*DefaultUserReply, error) {
	out := new(DefaultUserReply)
	err := c.cc.Invoke(ctx, "/proto.Scan/DefaultUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scanClient) ProcessScan(ctx context.Context, in *ProcessScanRequest, opts ...grpc.CallOption) (*ProcessScanReply, error) {
	out := new(ProcessScanReply)
	err := c.cc.Invoke(ctx, "/proto.Scan/ProcessScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scanClient) Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertReply, error) {
	out := new(ConvertReply)
	err := c.cc.Invoke(ctx, "/proto.Scan/Convert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScanServer is the server API for Scan service.
// All implementations must embed UnimplementedScanServer
// for forward compatibility
type ScanServer interface {
	DefaultUser(context.Context, *DefaultUserRequest) (*DefaultUserReply, error)
	ProcessScan(context.Context, *ProcessScanRequest) (*ProcessScanReply, error)
	Convert(context.Context, *ConvertRequest) (*ConvertReply, error)
	mustEmbedUnimplementedScanServer()
}

// UnimplementedScanServer must be embedded to have forward compatible implementations.
type UnimplementedScanServer struct {
}

func (UnimplementedScanServer) DefaultUser(context.Context, *DefaultUserRequest) (*DefaultUserReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DefaultUser not implemented")
}
func (UnimplementedScanServer) ProcessScan(context.Context, *ProcessScanRequest) (*ProcessScanReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessScan not implemented")
}
func (UnimplementedScanServer) Convert(context.Context, *ConvertRequest) (*ConvertReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Convert not implemented")
}
func (UnimplementedScanServer) mustEmbedUnimplementedScanServer() {}

// UnsafeScanServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScanServer will
// result in compilation errors.
type UnsafeScanServer interface {
	mustEmbedUnimplementedScanServer()
}

func RegisterScanServer(s grpc.ServiceRegistrar, srv ScanServer) {
	s.RegisterService(&Scan_ServiceDesc, srv)
}

func _Scan_DefaultUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServer).DefaultUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scan/DefaultUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServer).DefaultUser(ctx, req.(*DefaultUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scan_ProcessScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServer).ProcessScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scan/ProcessScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServer).ProcessScan(ctx, req.(*ProcessScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scan_Convert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServer).Convert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scan/Convert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServer).Convert(ctx, req.(*ConvertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Scan_ServiceDesc is the grpc.ServiceDesc for Scan service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Scan_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Scan",
	HandlerType: (*ScanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DefaultUser",
			Handler:    _Scan_DefaultUser_Handler,
		},
		{
			MethodName: "ProcessScan",
			Handler:    _Scan_ProcessScan_Handler,
		},
		{
			MethodName: "Convert",
			Handler:    _Scan_Convert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scan2drive.proto",
}
