// vim:ts=2:sw=2:et

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.16.0
// source: scan2drive.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DefaultUserRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DefaultUserRequest) Reset() {
	*x = DefaultUserRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan2drive_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultUserRequest) ProtoMessage() {}

func (x *DefaultUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan2drive_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultUserRequest.ProtoReflect.Descriptor instead.
func (*DefaultUserRequest) Descriptor() ([]byte, []int) {
	return file_scan2drive_proto_rawDescGZIP(), []int{0}
}

type DefaultUserReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User     string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	FullName string `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
}

func (x *DefaultUserReply) Reset() {
	*x = DefaultUserReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan2drive_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DefaultUserReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DefaultUserReply) ProtoMessage() {}

func (x *DefaultUserReply) ProtoReflect() protoreflect.Message {
	mi := &file_scan2drive_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DefaultUserReply.ProtoReflect.Descriptor instead.
func (*DefaultUserReply) Descriptor() ([]byte, []int) {
	return file_scan2drive_proto_rawDescGZIP(), []int{1}
}

func (x *DefaultUserReply) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *DefaultUserReply) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type ProcessScanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Dir  string `protobuf:"bytes,2,opt,name=dir,proto3" json:"dir,omitempty"`
}

func (x *ProcessScanRequest) Reset() {
	*x = ProcessScanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan2drive_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessScanRequest) ProtoMessage() {}

func (x *ProcessScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan2drive_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessScanRequest.ProtoReflect.Descriptor instead.
func (*ProcessScanRequest) Descriptor() ([]byte, []int) {
	return file_scan2drive_proto_rawDescGZIP(), []int{2}
}

func (x *ProcessScanRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ProcessScanRequest) GetDir() string {
	if x != nil {
		return x.Dir
	}
	return ""
}

type ProcessScanReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProcessScanReply) Reset() {
	*x = ProcessScanReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan2drive_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessScanReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessScanReply) ProtoMessage() {}

func (x *ProcessScanReply) ProtoReflect() protoreflect.Message {
	mi := &file_scan2drive_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessScanReply.ProtoReflect.Descriptor instead.
func (*ProcessScanReply) Descriptor() ([]byte, []int) {
	return file_scan2drive_proto_rawDescGZIP(), []int{3}
}

type ConvertRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ScannedPage [][]byte `protobuf:"bytes,1,rep,name=scanned_page,json=scannedPage,proto3" json:"scanned_page,omitempty"`
}

func (x *ConvertRequest) Reset() {
	*x = ConvertRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan2drive_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertRequest) ProtoMessage() {}

func (x *ConvertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scan2drive_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertRequest.ProtoReflect.Descriptor instead.
func (*ConvertRequest) Descriptor() ([]byte, []int) {
	return file_scan2drive_proto_rawDescGZIP(), []int{4}
}

func (x *ConvertRequest) GetScannedPage() [][]byte {
	if x != nil {
		return x.ScannedPage
	}
	return nil
}

type ConvertReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PDF []byte `protobuf:"bytes,1,opt,name=PDF,proto3" json:"PDF,omitempty"`
	// A thumbnail (PNG).
	Thumb []byte `protobuf:"bytes,2,opt,name=thumb,proto3" json:"thumb,omitempty"`
}

func (x *ConvertReply) Reset() {
	*x = ConvertReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_scan2drive_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConvertReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConvertReply) ProtoMessage() {}

func (x *ConvertReply) ProtoReflect() protoreflect.Message {
	mi := &file_scan2drive_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConvertReply.ProtoReflect.Descriptor instead.
func (*ConvertReply) Descriptor() ([]byte, []int) {
	return file_scan2drive_proto_rawDescGZIP(), []int{5}
}

func (x *ConvertReply) GetPDF() []byte {
	if x != nil {
		return x.PDF
	}
	return nil
}

func (x *ConvertReply) GetThumb() []byte {
	if x != nil {
		return x.Thumb
	}
	return nil
}

var File_scan2drive_proto protoreflect.FileDescriptor

var file_scan2drive_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x63, 0x61, 0x6e, 0x32, 0x64, 0x72, 0x69, 0x76, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x43, 0x0a, 0x10, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c,
	0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3a, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53,
	0x63, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x10,
	0x0a, 0x03, 0x64, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x64, 0x69, 0x72,
	0x22, 0x12, 0x0a, 0x10, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x63, 0x61, 0x6e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x33, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x63, 0x61, 0x6e, 0x6e, 0x65,
	0x64, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0b, 0x73, 0x63,
	0x61, 0x6e, 0x6e, 0x65, 0x64, 0x50, 0x61, 0x67, 0x65, 0x22, 0x36, 0x0a, 0x0c, 0x43, 0x6f, 0x6e,
	0x76, 0x65, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x44, 0x46,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x50, 0x44, 0x46, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x68, 0x75, 0x6d, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x74, 0x68, 0x75, 0x6d,
	0x62, 0x32, 0xc9, 0x01, 0x0a, 0x04, 0x53, 0x63, 0x61, 0x6e, 0x12, 0x43, 0x0a, 0x0b, 0x44, 0x65,
	0x66, 0x61, 0x75, 0x6c, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x43, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x63, 0x61, 0x6e, 0x12, 0x19,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x63,
	0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x53, 0x63, 0x61, 0x6e, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x12,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43,
	0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x2e, 0x5a,
	0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x61, 0x70,
	0x65, 0x6c, 0x62, 0x65, 0x72, 0x67, 0x2f, 0x73, 0x63, 0x61, 0x6e, 0x32, 0x64, 0x72, 0x69, 0x76,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_scan2drive_proto_rawDescOnce sync.Once
	file_scan2drive_proto_rawDescData = file_scan2drive_proto_rawDesc
)

func file_scan2drive_proto_rawDescGZIP() []byte {
	file_scan2drive_proto_rawDescOnce.Do(func() {
		file_scan2drive_proto_rawDescData = protoimpl.X.CompressGZIP(file_scan2drive_proto_rawDescData)
	})
	return file_scan2drive_proto_rawDescData
}

var file_scan2drive_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_scan2drive_proto_goTypes = []interface{}{
	(*DefaultUserRequest)(nil), // 0: proto.DefaultUserRequest
	(*DefaultUserReply)(nil),   // 1: proto.DefaultUserReply
	(*ProcessScanRequest)(nil), // 2: proto.ProcessScanRequest
	(*ProcessScanReply)(nil),   // 3: proto.ProcessScanReply
	(*ConvertRequest)(nil),     // 4: proto.ConvertRequest
	(*ConvertReply)(nil),       // 5: proto.ConvertReply
}
var file_scan2drive_proto_depIdxs = []int32{
	0, // 0: proto.Scan.DefaultUser:input_type -> proto.DefaultUserRequest
	2, // 1: proto.Scan.ProcessScan:input_type -> proto.ProcessScanRequest
	4, // 2: proto.Scan.Convert:input_type -> proto.ConvertRequest
	1, // 3: proto.Scan.DefaultUser:output_type -> proto.DefaultUserReply
	3, // 4: proto.Scan.ProcessScan:output_type -> proto.ProcessScanReply
	5, // 5: proto.Scan.Convert:output_type -> proto.ConvertReply
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_scan2drive_proto_init() }
func file_scan2drive_proto_init() {
	if File_scan2drive_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_scan2drive_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultUserRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan2drive_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DefaultUserReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan2drive_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessScanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan2drive_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessScanReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan2drive_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvertRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_scan2drive_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConvertReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_scan2drive_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scan2drive_proto_goTypes,
		DependencyIndexes: file_scan2drive_proto_depIdxs,
		MessageInfos:      file_scan2drive_proto_msgTypes,
	}.Build()
	File_scan2drive_proto = out.File
	file_scan2drive_proto_rawDesc = nil
	file_scan2drive_proto_goTypes = nil
	file_scan2drive_proto_depIdxs = nil
}
