// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scan2drive.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DefaultUserRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultUserRequest) Reset()         { *m = DefaultUserRequest{} }
func (m *DefaultUserRequest) String() string { return proto.CompactTextString(m) }
func (*DefaultUserRequest) ProtoMessage()    {}
func (*DefaultUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b328f58df121c91, []int{0}
}

func (m *DefaultUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultUserRequest.Unmarshal(m, b)
}
func (m *DefaultUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultUserRequest.Marshal(b, m, deterministic)
}
func (m *DefaultUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultUserRequest.Merge(m, src)
}
func (m *DefaultUserRequest) XXX_Size() int {
	return xxx_messageInfo_DefaultUserRequest.Size(m)
}
func (m *DefaultUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultUserRequest proto.InternalMessageInfo

type DefaultUserReply struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	FullName             string   `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DefaultUserReply) Reset()         { *m = DefaultUserReply{} }
func (m *DefaultUserReply) String() string { return proto.CompactTextString(m) }
func (*DefaultUserReply) ProtoMessage()    {}
func (*DefaultUserReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b328f58df121c91, []int{1}
}

func (m *DefaultUserReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DefaultUserReply.Unmarshal(m, b)
}
func (m *DefaultUserReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DefaultUserReply.Marshal(b, m, deterministic)
}
func (m *DefaultUserReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DefaultUserReply.Merge(m, src)
}
func (m *DefaultUserReply) XXX_Size() int {
	return xxx_messageInfo_DefaultUserReply.Size(m)
}
func (m *DefaultUserReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DefaultUserReply.DiscardUnknown(m)
}

var xxx_messageInfo_DefaultUserReply proto.InternalMessageInfo

func (m *DefaultUserReply) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *DefaultUserReply) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

type ProcessScanRequest struct {
	User                 string   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Dir                  string   `protobuf:"bytes,2,opt,name=dir,proto3" json:"dir,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessScanRequest) Reset()         { *m = ProcessScanRequest{} }
func (m *ProcessScanRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessScanRequest) ProtoMessage()    {}
func (*ProcessScanRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b328f58df121c91, []int{2}
}

func (m *ProcessScanRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessScanRequest.Unmarshal(m, b)
}
func (m *ProcessScanRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessScanRequest.Marshal(b, m, deterministic)
}
func (m *ProcessScanRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessScanRequest.Merge(m, src)
}
func (m *ProcessScanRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessScanRequest.Size(m)
}
func (m *ProcessScanRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessScanRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessScanRequest proto.InternalMessageInfo

func (m *ProcessScanRequest) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ProcessScanRequest) GetDir() string {
	if m != nil {
		return m.Dir
	}
	return ""
}

type ProcessScanReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessScanReply) Reset()         { *m = ProcessScanReply{} }
func (m *ProcessScanReply) String() string { return proto.CompactTextString(m) }
func (*ProcessScanReply) ProtoMessage()    {}
func (*ProcessScanReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b328f58df121c91, []int{3}
}

func (m *ProcessScanReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessScanReply.Unmarshal(m, b)
}
func (m *ProcessScanReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessScanReply.Marshal(b, m, deterministic)
}
func (m *ProcessScanReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessScanReply.Merge(m, src)
}
func (m *ProcessScanReply) XXX_Size() int {
	return xxx_messageInfo_ProcessScanReply.Size(m)
}
func (m *ProcessScanReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessScanReply.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessScanReply proto.InternalMessageInfo

type ConvertRequest struct {
	ScannedPage          [][]byte `protobuf:"bytes,1,rep,name=scanned_page,json=scannedPage,proto3" json:"scanned_page,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConvertRequest) Reset()         { *m = ConvertRequest{} }
func (m *ConvertRequest) String() string { return proto.CompactTextString(m) }
func (*ConvertRequest) ProtoMessage()    {}
func (*ConvertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b328f58df121c91, []int{4}
}

func (m *ConvertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertRequest.Unmarshal(m, b)
}
func (m *ConvertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertRequest.Marshal(b, m, deterministic)
}
func (m *ConvertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertRequest.Merge(m, src)
}
func (m *ConvertRequest) XXX_Size() int {
	return xxx_messageInfo_ConvertRequest.Size(m)
}
func (m *ConvertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertRequest proto.InternalMessageInfo

func (m *ConvertRequest) GetScannedPage() [][]byte {
	if m != nil {
		return m.ScannedPage
	}
	return nil
}

type ConvertReply struct {
	PDF []byte `protobuf:"bytes,1,opt,name=PDF,proto3" json:"PDF,omitempty"`
	// A thumbnail (PNG).
	Thumb                []byte   `protobuf:"bytes,2,opt,name=thumb,proto3" json:"thumb,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConvertReply) Reset()         { *m = ConvertReply{} }
func (m *ConvertReply) String() string { return proto.CompactTextString(m) }
func (*ConvertReply) ProtoMessage()    {}
func (*ConvertReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_0b328f58df121c91, []int{5}
}

func (m *ConvertReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConvertReply.Unmarshal(m, b)
}
func (m *ConvertReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConvertReply.Marshal(b, m, deterministic)
}
func (m *ConvertReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConvertReply.Merge(m, src)
}
func (m *ConvertReply) XXX_Size() int {
	return xxx_messageInfo_ConvertReply.Size(m)
}
func (m *ConvertReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ConvertReply.DiscardUnknown(m)
}

var xxx_messageInfo_ConvertReply proto.InternalMessageInfo

func (m *ConvertReply) GetPDF() []byte {
	if m != nil {
		return m.PDF
	}
	return nil
}

func (m *ConvertReply) GetThumb() []byte {
	if m != nil {
		return m.Thumb
	}
	return nil
}

func init() {
	proto.RegisterType((*DefaultUserRequest)(nil), "proto.DefaultUserRequest")
	proto.RegisterType((*DefaultUserReply)(nil), "proto.DefaultUserReply")
	proto.RegisterType((*ProcessScanRequest)(nil), "proto.ProcessScanRequest")
	proto.RegisterType((*ProcessScanReply)(nil), "proto.ProcessScanReply")
	proto.RegisterType((*ConvertRequest)(nil), "proto.ConvertRequest")
	proto.RegisterType((*ConvertReply)(nil), "proto.ConvertReply")
}

func init() { proto.RegisterFile("scan2drive.proto", fileDescriptor_0b328f58df121c91) }

var fileDescriptor_0b328f58df121c91 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4f, 0xc2, 0x40,
	0x10, 0xc5, 0xa9, 0x80, 0xca, 0xd0, 0x98, 0x66, 0xc4, 0x58, 0xf1, 0x82, 0x7b, 0xe2, 0xc4, 0x01,
	0x12, 0x4d, 0xbc, 0x96, 0x78, 0x34, 0x4d, 0x8d, 0x67, 0xb2, 0xb4, 0x03, 0x92, 0xf4, 0x9f, 0xbb,
	0x5d, 0x12, 0x3e, 0xa2, 0xdf, 0xca, 0xec, 0xb2, 0x36, 0xd4, 0x72, 0xda, 0xd9, 0x37, 0x3b, 0xbf,
	0xd9, 0xf7, 0xc0, 0x93, 0x31, 0xcf, 0xe7, 0x89, 0xd8, 0xed, 0x69, 0x56, 0x8a, 0xa2, 0x2a, 0xb0,
	0x6f, 0x0e, 0x36, 0x02, 0x5c, 0xd2, 0x86, 0xab, 0xb4, 0xfa, 0x94, 0x24, 0x22, 0xfa, 0x56, 0x24,
	0x2b, 0x16, 0x80, 0xd7, 0x50, 0xcb, 0xf4, 0x80, 0x08, 0x3d, 0x25, 0x49, 0xf8, 0xce, 0xc4, 0x99,
	0x0e, 0x22, 0x53, 0xe3, 0x23, 0x0c, 0x36, 0x2a, 0x4d, 0x57, 0x39, 0xcf, 0xc8, 0xbf, 0x30, 0x8d,
	0x6b, 0x2d, 0xbc, 0xf3, 0x8c, 0xd8, 0x2b, 0x60, 0x28, 0x8a, 0x98, 0xa4, 0xfc, 0x88, 0x79, 0x6e,
	0xd1, 0x67, 0x31, 0x1e, 0x74, 0x93, 0x9d, 0xb0, 0x00, 0x5d, 0x32, 0x04, 0xaf, 0x31, 0x5b, 0xa6,
	0x07, 0xb6, 0x80, 0x9b, 0xa0, 0xc8, 0xf7, 0x24, 0xaa, 0x3f, 0xd6, 0x13, 0xb8, 0xda, 0x57, 0x4e,
	0xc9, 0xaa, 0xe4, 0x5b, 0xf2, 0x9d, 0x49, 0x77, 0xea, 0x46, 0x43, 0xab, 0x85, 0x7c, 0x4b, 0xec,
	0x19, 0xdc, 0x7a, 0x48, 0xbb, 0xf0, 0xa0, 0x1b, 0x2e, 0xdf, 0xcc, 0x76, 0x37, 0xd2, 0x25, 0x8e,
	0xa0, 0x5f, 0x7d, 0xa9, 0x6c, 0x6d, 0xd6, 0xbb, 0xd1, 0xf1, 0x32, 0xff, 0x71, 0xa0, 0xa7, 0x57,
	0x63, 0x00, 0xc3, 0x93, 0x28, 0xf0, 0xe1, 0x18, 0xdf, 0xac, 0x1d, 0xda, 0xf8, 0xfe, 0x5c, 0x4b,
	0x7f, 0xbc, 0xa3, 0x21, 0x27, 0x76, 0x6a, 0x48, 0x3b, 0x9e, 0x1a, 0xd2, 0x72, 0xdf, 0xc1, 0x17,
	0xb8, 0xb2, 0x56, 0xf0, 0xce, 0xbe, 0x6a, 0xe6, 0x31, 0xbe, 0xfd, 0x2f, 0x9b, 0xc1, 0xf5, 0xa5,
	0x51, 0x17, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x85, 0x81, 0x01, 0xa1, 0x05, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ScanClient is the client API for Scan service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ScanClient interface {
	DefaultUser(ctx context.Context, in *DefaultUserRequest, opts ...grpc.CallOption) (*DefaultUserReply, error)
	ProcessScan(ctx context.Context, in *ProcessScanRequest, opts ...grpc.CallOption) (*ProcessScanReply, error)
	Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertReply, error)
}

type scanClient struct {
	cc *grpc.ClientConn
}

func NewScanClient(cc *grpc.ClientConn) ScanClient {
	return &scanClient{cc}
}

func (c *scanClient) DefaultUser(ctx context.Context, in *DefaultUserRequest, opts ...grpc.CallOption) (*DefaultUserReply, error) {
	out := new(DefaultUserReply)
	err := c.cc.Invoke(ctx, "/proto.Scan/DefaultUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scanClient) ProcessScan(ctx context.Context, in *ProcessScanRequest, opts ...grpc.CallOption) (*ProcessScanReply, error) {
	out := new(ProcessScanReply)
	err := c.cc.Invoke(ctx, "/proto.Scan/ProcessScan", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scanClient) Convert(ctx context.Context, in *ConvertRequest, opts ...grpc.CallOption) (*ConvertReply, error) {
	out := new(ConvertReply)
	err := c.cc.Invoke(ctx, "/proto.Scan/Convert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScanServer is the server API for Scan service.
type ScanServer interface {
	DefaultUser(context.Context, *DefaultUserRequest) (*DefaultUserReply, error)
	ProcessScan(context.Context, *ProcessScanRequest) (*ProcessScanReply, error)
	Convert(context.Context, *ConvertRequest) (*ConvertReply, error)
}

func RegisterScanServer(s *grpc.Server, srv ScanServer) {
	s.RegisterService(&_Scan_serviceDesc, srv)
}

func _Scan_DefaultUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServer).DefaultUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scan/DefaultUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServer).DefaultUser(ctx, req.(*DefaultUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scan_ProcessScan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessScanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServer).ProcessScan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scan/ProcessScan",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServer).ProcessScan(ctx, req.(*ProcessScanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scan_Convert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConvertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScanServer).Convert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Scan/Convert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScanServer).Convert(ctx, req.(*ConvertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scan_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Scan",
	HandlerType: (*ScanServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DefaultUser",
			Handler:    _Scan_DefaultUser_Handler,
		},
		{
			MethodName: "ProcessScan",
			Handler:    _Scan_ProcessScan_Handler,
		},
		{
			MethodName: "Convert",
			Handler:    _Scan_Convert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scan2drive.proto",
}
