	// gas: ld3 {v10.b, v11.b, v12.b}[0], [RGB], #3
	// obj: ld3 {v10.b-v12.b}[0], [x7], #3
	WORD $0x0ddf20ea
	// gas: ld3 {v10.b, v11.b, v12.b}[1], [RGB], #3
	// obj: ld3 {v10.b-v12.b}[1], [x7], #3
	WORD $0x0ddf24ea
	// gas: ld3 {v10.b, v11.b, v12.b}[2], [RGB], #3
	// obj: ld3 {v10.b-v12.b}[2], [x7], #3
	WORD $0x0ddf28ea
	// gas: ld3 {v10.b, v11.b, v12.b}[3], [RGB], #3
	// obj: ld3 {v10.b-v12.b}[3], [x7], #3
	WORD $0x0ddf2cea
