package templates

// Generated by "go run gentmpl.go Index Setup".
// Do not edit manually.

import (
	"html/template"
)

var IndexTpl = template.Must(template.New("Index").Parse(`<!DOCTYPE html>
<html>
<head>
<meta http-equiv="X-UA-Compatible" content="chrome=1" />
<meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,700">
<link rel="import" href="/assets/elements.vulcanized.html" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script type="text/javascript" src="/constants.js"></script>
<script type="text/javascript" src="/assets/scan2drive.js"></script>
<style is="custom-style" include="iron-flex iron-flex-alignment">
body {
	margin: 0;
	padding: 0;
}
#content {
	padding-left: 1em;
	padding-right: 1em;
}
p,div {
    @apply(--paper-font-body1);
}
h1 {
    @apply(--paper-font-display1);
}
.container {
	@apply(--layout-horizontal);
}
.container > div {
	margin-left: 1em;
	margin-right: 1em;
}
.flexchild {
	@apply(--layout-flex);
}
#user-avatar {
	border-radius: 50%;
	height: 32px;
	width: 32px;
	margin-left: 0.5em;
}
#scanfab {
	position: fixed;
	bottom: 16px;
	right: 16px;
}

paper-card.scan {
	@apply(--layout-horizontal);
	margin-bottom: 1em;
}
paper-card.scan .card-actions {
	position: absolute;
	bottom: 0;
	width: 90%;
}
.scan-content {
	@apply(--layout-flex);
	float: left;
	position: relative;
}
.scan-status {
	vertical-align: middle;
}
.scan-title {
	@apply(--paper-font-headline);
	margin-bottom: .5em;
}
.scan-thumb {
	/* These dimensions are a 600 dpi scan divided by 7. */
	width: 170px;
	height: 240px;
}
.signin {
	border: 1px solid #d9d9d9;
}
.user-avatar-wrapper {
	margin-left: 1em;
	@apply(--layout-horizontal);
}
.user-avatar-wrapper a, .user-avatar-wrapper a:hover, .user-avatar-wrapper a:visited {
	color: white;
}
.user-avatar-wrapper div {
	font-size: 13px;
	line-height: 16px;
}
.paper-toolbar-0 .toolbar-tools.paper-toolbar .title {
	margin-left: 0;
}
paper-toolbar {
	margin-bottom: 1em;
}
.scan-progress {
	@apply(--layout-horizontal);
}
.scan-progress paper-spinner-lite {
	margin-right: 1em;
}
#scan-dialog {
	@apply(--layout-horizontal);
}
</style>
</head>
<body>

<paper-fab style="display: none; z-index: 1" id="scanfab" icon="hardware:scanner" title="Scan" onclick="scan()"></paper-fab>

<paper-toolbar>
	<span class="title">scan2drive</span>
	<!-- TODO: settings drawer: default user account for scan button, drive folder to upload to -->
	<paper-icon-button id="settings-button" style="display: none" icon="settings" onclick="document.getElementById('settings-dialog').open()"></paper-icon-button>
	<div class="user-avatar-wrapper">
	  <div>
	  <span id="user-name" data-sub="{{ .sub }}">Not logged in</span><br>
	  <a href="#" id="signout" style="display: none">Sign out</a>
	  </div>
	  <img id="user-avatar" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNgYAAAAAMAASsJTYQAAAAASUVORK5CYII=">
	</div>
</paper-toolbar>

<paper-dialog id="settings-dialog" entry-animation="scale-up-animation" exit-animation="fade-out-animation" with-backdrop style="min-width: 50%">
	<h2>Settings</h2>
	<!-- TODO: make this dialog prettier -->
	<div>
	<paper-input-container>
		<!-- TODO: style this as a material design label -->
		<label>Drive folder to store scans in</label><br>
		<paper-button id="select-drive-folder" style="float: right"><iron-icon icon="folder"></iron-icon>select</paper-button>
		<p id="drive-folder">
		{{ if eq .user.Folder.Id "" }}
			<span style="color: red">No drive folder selected</span>
		{{ else }}
			<img src="{{ .user.Folder.IconUrl }}" style="margin-right: 0.25em">
			<a href="{{ .user.Folder.Url }}">{{ .user.Folder.Name }}</a>
		{{ end }}
		</p>
	</paper-input-container>
	<paper-button dialog-confirm>close</paper-button>
	</div>
	<!-- TODO: <p>Default account</p>
	<p>acc</p> -->
</paper-dialog>

<paper-dialog id="scan-dialog" entry-animation="scale-up-animation" exit-animation="fade-out-animation" with-backdrop style="min-width: 50%">
  <div class="scan-dialog-content">
    <h2>Scan</h2>
    <div class="scan-progress">
    <paper-spinner-lite active></paper-spinner-lite>
    <span id="scan-progress-status">Scanning pages…</span>
    </div>
    <form is="iron-form" method="get" action="#" id="scan-form">
      <paper-input name="name" label="Name" required always-float-label>
        <div prefix></div>
  	  <iron-icon icon="done" style="display: none" suffix></iron-icon>
  	</paper-input>
      <paper-button raised>Rename scan</paper-button>
    </form>
  </div>
  <!-- TODO: make scan-thumb zoomable (use “list” neon-animate) -->
  <div class="scan-thumb"></div>
</paper-dialog>

<div id="content">
<div id="signin">
<p>
scan2drive’s purpose is to store scans on Google Drive, so please <custom-google-signin></custom-google-signin>
</p>
</div>
<div id="error">
  <p></p>
</div>
{{ range $key := .keys }}
{{ with $scan := index $.scans $key }}
{{ if eq $scan.Sub $.sub }}
<paper-card class="scan">
	<div class="scan-content">
		<div class="card-content">
			<p class="scan-title">
			<!-- TODO: retro-active rename, i.e. make this name clickable and implement a rename handler -->
			{{ if eq $scan.NewName "" }}
			{{ $key }}
			{{ else }}
			{{ $key }}-{{ $scan.NewName }}
			{{ end }}
			</p>
			<div class="scan-status">
				{{ if (not $scan.Converted) }}
				<iron-icon icon="cloud-queue"></iron-icon>
				<span>queued for conversion</span>
				{{ else if (or (not $scan.UploadedOriginals) (not $scan.UploadedPDF)) }}
				<iron-icon icon="cloud-upload"></iron-icon>
				<span>uploading</span>
				{{ else }}
				<iron-icon icon="cloud-done"></iron-icon>
				<span>done</span>
				{{ end }}
			</div>
		</div>
		<div class="card-actions">
			<paper-button><iron-icon src="/assets/drive48.png"></iron-icon>view in drive</paper-button>
		</div>
	</div>
	<div class="scan-thumb" style="background: url('scans_dir/{{ $scan.Sub }}/{{ $key }}/thumb.png'); background-size: cover"></div>
</paper-card>
{{ end }}
{{ end }}
{{ end }}
</div>
<script src="https://apis.google.com/js/client:platform.js?onload=start" async defer></script>
</body>
</html>
`))

var SetupTpl = template.Must(template.New("Setup").Parse(`<!DOCTYPE html>
<html>
<head>
<title>scan2drive: setup</title>
<meta http-equiv="X-UA-Compatible" content="chrome=1" />
<meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,700">
<link rel="import" href="/assets/elements.vulcanized.html" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script type="text/javascript" src="/assets/scan2drive.js"></script>
<style is="custom-style" include="iron-flex iron-flex-alignment">
body {
	margin: 0;
	padding: 0;
}
#content {
	padding-left: 1em;
	padding-right: 1em;
}
p,div {
    @apply(--paper-font-body1);
}
h1 {
    @apply(--paper-font-display1);
}
.container {
	@apply(--layout-horizontal);
}
.container > div {
	margin-left: 1em;
	margin-right: 1em;
}
.flexchild {
	@apply(--layout-flex);
}
#user-avatar {
	border-radius: 50%;
	height: 32px;
	width: 32px;
	margin-left: 0.5em;
}
#scanfab {
	position: fixed;
	bottom: 16px;
	right: 16px;
}

paper-card.scan {
	@apply(--layout-horizontal);
	margin-bottom: 1em;
}
paper-card.scan .card-actions {
	position: absolute;
	bottom: 0;
	width: 90%;
}
.scan-content {
	@apply(--layout-flex);
	float: left;
	position: relative;
}
.scan-status {
	vertical-align: middle;
}
.scan-title {
	@apply(--paper-font-headline);
	margin-bottom: .5em;
}
.scan-thumb {
	/* These dimensions are a 600 dpi scan divided by 7. */
	width: 170px;
	height: 240px;
}
.signin {
	border: 1px solid #d9d9d9;
}
.user-avatar-wrapper {
	margin-left: 1em;
	@apply(--layout-horizontal);
}
.user-avatar-wrapper a, .user-avatar-wrapper a:hover, .user-avatar-wrapper a:visited {
	color: white;
}
.user-avatar-wrapper div {
	font-size: 13px;
	line-height: 16px;
}
.paper-toolbar-0 .toolbar-tools.paper-toolbar .title {
	margin-left: 0;
}
paper-toolbar {
	margin-bottom: 1em;
}
.scan-progress {
	@apply(--layout-horizontal);
}
.scan-progress paper-spinner-lite {
	margin-right: 1em;
}
#scan-dialog {
	@apply(--layout-horizontal);
}
</style>
</head>
<body>

<paper-fab style="display: none; z-index: 1" id="scanfab" icon="hardware:scanner" title="Scan" onclick="scan()"></paper-fab>

<paper-toolbar>
	<span class="title">scan2drive</span>
	<!-- TODO: settings drawer: default user account for scan button, drive folder to upload to -->
	<paper-icon-button id="settings-button" style="display: none" icon="settings" onclick="document.getElementById('settings-dialog').open()"></paper-icon-button>
	<div class="user-avatar-wrapper">
	  <div>
	  <span id="user-name" data-sub="{{ .sub }}">Not logged in</span><br>
	  <a href="#" id="signout" style="display: none">Sign out</a>
	  </div>
	  <img id="user-avatar" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNgYAAAAAMAASsJTYQAAAAASUVORK5CYII=">
	</div>
</paper-toolbar>

<div id="content">
<h1>Initial Setup</h1>
<p>
You’re seeing this page because the OAuth client secret could not be read from <code>{{ .ClientSecretPath }}</code> (configured via the <code>-client_secret_path</code> flag).
</p>
<ol>
<li>Use <a href="https://console.developers.google.com/start/api?id=drive">Google’s wizard</a> to create a new cloud project and turn on the Drive API.</li>
<li>On the <strong>Add credentials to your project</strong> page, click the Cancel button.</li>
<li>At the top of the page, select the <strong>OAuth consent screen</strong> tab. Select an <strong>Email address</strong>, enter a <strong>Product name</strong>, and click the <strong>Save</strong> button.</li>
<li>Select the <strong>Credentials</strong> tab, click the <strong>Create credentials</strong> button and select <strong>OAuth client ID</strong>.</li>
<li>Select the application type <strong>Web application</strong>, enter the name “scan2drive”, add the URLs under which you are going to access scan2drive to <strong>Authorized JavaScript origins</strong> (e.g. <code>http://localhost:7120</code> and <code>http://scan2drive.lan:7120</code>), and click the <strong>Create</strong> button.</li>
{{ if .CanWriteClientSecret }}
<li>Copy &amp; paste the values into this form:

  <form method="post" action="/setup" id="setup-form">
    <label for="clientid">Client ID:</label><br>
    <input id="clientid" name="clientid" label="Client ID" required placeholder="Client ID (ending in .apps.googleusercontent.com)" style="width: 100%"><br>

    <label for="clientsecret">Client secret:</label><br>
    <input id="clientsecret" name="clientsecret" label="Client secret" required placeholder="Client secret" style="width: 100%"><br>

    <button type="submit">Setup</button>
  </form>

</li>
{{ end }}
</ol>
</div>
</div>
<script src="https://apis.google.com/js/client:platform.js?onload=start" async defer></script>
</body>
</html>
`))
