package templates

// Generated by "go run gentmpl.go Index Setup".
// Do not edit manually.

import (
	"html/template"
)

var IndexTpl = template.Must(template.New("Index").Parse(`<!DOCTYPE html>
<html>
<head>
<title>scan2drive</title>
<meta http-equiv="X-UA-Compatible" content="chrome=1" />
<meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,700">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
<style type="text/css">
/* workaround for https://github.com/Dogfalo/materialize/issues/1727 */
.picker {
  font-size: initial;
  text-align: initial;
  line-height: initial;
  color: initial;
  position: initial;
  z-index: initial;
  -webkit-user-select: initial;
  -moz-user-select: initial;
  -ms-user-select: initial;
  user-select: initial;
}
.modal-overlay {
  z-index: 998 !important;
}
#settings-dialog {
  z-index: 999 !important;
}
</style>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
<script type="text/javascript" src="/constants.js"></script>
<script type="text/javascript" src="/assets/scan2drive.js"></script>
<style is="custom-style" include="iron-flex iron-flex-alignment">
body {
	margin: 0;
	padding: 0;
}
#user-avatar, .user-avatar {
	border-radius: 50%;
	height: 32px;
	width: 32px;
	margin-left: 0.5em;
}
.user-avatar {
	float: left;
	margin-right: 0.5em;
}
.user-nick {
	line-height: 32px;
}
.user {
	margin-bottom: 1em;
	cursor: pointer;
}
.user:hover {
	background-color: #eee;
}
.default-user {
	font-weight: bold;
}
.scan-thumb {
	/* These dimensions are a 600 dpi scan divided by 7. */
	width: 170px;
	height: 240px;
}
#signout {
	font-size: 13px;
	text-decoration: underline;
	padding: 0;
	transition: color 0s;
	background-color: rgb(92, 107, 192);
	display: inline;
}
.status i {
	margin-right: 0.5em;
}
</style>
</head>
<body>
  
  <nav class="indigo lighten-1" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="#" class="brand-logo">scan2drive</a>
      
      <ul class="right hide-on-med-and-down valign-wrapper">
	<li><a href="#settings-dialog"><i class="material-icons">settings</i></a></li>
	<li><a href="#people-dialog"><i class="material-icons">people</i></a></li>
	<li class="valign-wrapper" style="line-height: 16px; margin-left: 1em">
	  <div>
	    <span id="user-name" data-sub="{{ .sub }}">Not logged in</span><br>
	    <a href="#" id="signout" style="display: none">Sign out</a>
	  </div>
	  <img id="user-avatar" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNgYAAAAAMAASsJTYQAAAAASUVORK5CYII=" class="circle responsive-img valign">
	</li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="#"><i class="material-icons">settings</i></a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  
  <div class="fixed-action-btn" display="none">
    <a class="btn-floating btn-large waves-effect waves-light red" onclick="scan()"
       {{ if (ne .defaultscantarget.Name "") }}
       title="Scan from {{ .defaultscantarget.Name }}"
       {{ end }}
       >
      {{ if (and (ne .defaultscantarget.Name "") (ne .defaultscantarget.IconURL "")) }}
      <img src="{{ .defaultscantarget.IconURL }}" title="Scan from {{ .defaultscantarget.Name }}" alt="Scan from {{ .defaultscantarget.Name }}" width="32" height="32" style="top: 8px">
      {{ else if (ne .defaultscantarget.Name "") }}
      <i class="large material-icons" title="Scan from {{ .defaultscantarget.Name }}">scanner</i>
      {{ else }}
      <i class="large material-icons" title="Scan">scanner</i>
      {{ end }}
    </a>
  </div>

  <div id="settings-dialog" class="modal" style="min-width: 50%">
    <div class="modal-content">
      <h4>Settings</h4>

      <form action="#">
	<div class="file-field input-field">
	  <div class="btn" id="select-drive-folder">
	    <span>Folder</span>
	  </div>
	  <div class="file-path-wrapper">
	    <input id="drivefolder"
		   class="file-path validate"
		   type="text"
		   placeholder="Google Drive folder"
		   disabled="disabled"
		   {{ if ne .user.Folder.Id "" }}
		   value="{{ .user.Folder.Name }}"
		   {{ end }}
		   >
	  </div>
	</div>
      </form>
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Close</a>
    </div>
  </div>

  <div id="people-dialog" class="modal" style="min-width: 50%">
    <div class="modal-content">
      <h4>Default scan recipient</h4>

      <p>
	When pressing the physical scan button, scans should be received by:
      </p>

      <form action="#">
	{{ range $u := .users }}
	<div class="user {{ if eq $.defaultsub $u.Sub }}default-user{{ end }}" data-sub="{{ $u.Sub }}">
	  <img class="user-avatar" src="{{ $u.PictureURL }}" class="circle responsive-img valign">
	  <span class="user-nick">{{ $u.FullName }}</span>
	</div>
	{{ end }}
      </form>
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Close</a>
    </div>
  </div>

  <div id="scan-dialog" class="modal" style="min-width: 50%">
    <div class="modal-content">
      <h4>Scan</h4>

      <div class="progress">
	<!-- TODO: make this determinate once the server reports progress -->
	<div class="indeterminate"></div>
      </div>

      <span id="scan-progress-status">Scanning pages…</span>

      <form action="#">
	<div id="scan-name-prefix">
	  2017-05-20 17:18:00
	</div>
	<div class="input-field inline">
	  <input id="name" type="text">
	  <label for="name">Name</label>
	</div>
	<div class="btn">
	  <span>Rename scan</span>
	</div>
      </form>
      
      <!-- TODO: add (zoomable) scan-thumb so that the user can see what the document contains -->
    </div>
  </div>

  <div id="content">
    <div id="signin">
      <p>
	scan2drive’s purpose is to store scans on Google Drive, so please
	<div id="my-signin2"></div>
      </p>
    </div>
    <div id="error">
      <p></p>
    </div>
  </div>
  
  <div class="container">
    <div class="section">

{{ range $key := .keys }}
{{ with $scan := index $.scans $key }}
{{ if eq $scan.Sub $.sub }}
      <div class="row">
        <div class="col s12 m12">
	  <div class="card horizontal">
	    <div class="card-stacked">
              <div class="card-content">
		<span class="card-title">
			<!-- TODO: retro-active rename, i.e. make this name clickable and implement a rename handler -->
			{{ if eq $scan.NewName "" }}
			{{ $key }}
			{{ else }}
			{{ $key }}-{{ $scan.NewName }}
			{{ end }}
		</span>
		<p style="line-height: 24px" class="status valign-wrapper">
		  {{ if (not $scan.Converted) }}
		  <i class="material-icons">cloud_queue</i> queued for conversion
		  {{ else if (or (not $scan.UploadedOriginals) (not $scan.UploadedPDF)) }}
		  <i class="material-icons">cloud_upload</i> uploading
		  {{ else }}
		  <i class="material-icons">cloud_done</i> done
		  {{ end }}
		  
		</p>
              </div>
              <div class="card-action" style="line-height: 24px">
		<a href="https://drive.google.com/file/d/{{ $scan.PDFDriveId }}/view"><i class="material-icons left">cloud</i> View in drive</a>
              </div>
	    </div>
	    <div class="card-image">
	      <img class="scan-thumb" src="scans_dir/{{ $scan.Sub }}/{{ $key }}/thumb.png">
            </div>
	  </div>
        </div>
      </div>
{{ end }}
{{ end }}
{{ end }}
    </div>
  </div>

  <!--  Scripts-->
  <script type="text/javascript">
    $(document).ready(function() {
      $('#settings-dialog').modal();
      $('#people-dialog').modal();
      $('#scan-dialog').modal({
        dismissible: false // cannot be dismissed by clicking outside
      });
    });
  </script>
  <script src="https://apis.google.com/js/client:platform.js?onload=start" async defer></script>
  </body>
</html>
`))

var SetupTpl = template.Must(template.New("Setup").Parse(`<!DOCTYPE html>
<html>
<head>
<title>scan2drive: setup</title>
<meta http-equiv="X-UA-Compatible" content="chrome=1" />
<meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,700">
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/js/materialize.min.js"></script>
<style is="custom-style" include="iron-flex iron-flex-alignment">
body {
	margin: 0;
	padding: 0;
}
#user-avatar {
	border-radius: 50%;
	height: 32px;
	width: 32px;
	margin-left: 0.5em;
}
</style>
</head>
<body>
  
  <nav class="indigo lighten-1" role="navigation">
    <div class="nav-wrapper container">
      <a id="logo-container" href="#" class="brand-logo">scan2drive</a>
      
      <ul class="right hide-on-med-and-down valign-wrapper">
	<li><a href="#settings-dialog"><i class="material-icons">settings</i></a></li>
	<li class="valign-wrapper" style="line-height: 16px; margin-left: 1em">
	  <div>
	    <span id="user-name" data-sub="{{ .sub }}">Not logged in</span><br>
	    <a href="#" id="signout" style="display: none">Sign out</a>
	  </div>
	  <img id="user-avatar" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNgYAAAAAMAASsJTYQAAAAASUVORK5CYII=" class="circle responsive-img valign">
	</li>
      </ul>

      <ul id="nav-mobile" class="side-nav">
        <li><a href="#"><i class="material-icons">settings</i></a></li>
      </ul>
      <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
    </div>
  </nav>

  <div class="container">
    <div class="section">

      <div class="row">
        <div class="col s12 m12">

	  <h1>Initial Setup</h1>
<p>
You’re seeing this page because the OAuth client secret could not be read from <code>{{ .ClientSecretPath }}</code> (configured via the <code>-client_secret_path</code> flag).
</p>
<ol>
<li>Use <a href="https://console.developers.google.com/start/api?id=drive">Google’s wizard</a> to create a new cloud project and turn on the Drive API.</li>
<li>On the <strong>Add credentials to your project</strong> page, click the Cancel button.</li>
<li>At the top of the page, select the <strong>OAuth consent screen</strong> tab. Select an <strong>Email address</strong>, enter a <strong>Product name</strong>, and click the <strong>Save</strong> button.</li>
<li>Select the <strong>Credentials</strong> tab, click the <strong>Create credentials</strong> button and select <strong>OAuth client ID</strong>.</li>
<li>Select the application type <strong>Web application</strong>, enter the name “scan2drive”, add the URLs under which you are going to access scan2drive to <strong>Authorized JavaScript origins</strong> (e.g. <code>http://localhost:7120</code> and <code>http://scan2drive.lan:7120</code>), and click the <strong>Create</strong> button.</li>
{{ if .CanWriteClientSecret }}
<li>Copy &amp; paste the values into this form:

  <form method="post" action="/setup" id="setup-form">
    <label for="clientid">Client ID:</label><br>
    <input id="clientid" name="clientid" label="Client ID" required placeholder="Client ID (ending in .apps.googleusercontent.com)" style="width: 100%"><br>

    <label for="clientsecret">Client secret:</label><br>
    <input id="clientsecret" name="clientsecret" label="Client secret" required placeholder="Client secret" style="width: 100%"><br>

    <button type="submit">Setup</button>
  </form>

</li>
{{ else }}
<li>Dismiss the popup and click the download JSON button next to the newly created credential.</li>
<li>Avail the downloaded JSON credential file as <code>{{ .ClientSecretPath }}</code>.</li>
{{ end }}
</ol>

        </div>
      </div>
    </div>
  </div>

  </body>
</html>
`))
